# Cart Pole Variables:
gravity: 9.8
cart_mass_kg: 10
pole_mass_kg: 5
pole_len_m: 3

# Agent
learning_rate: 0.0001
start_epsilon: 1
epsilon_min: 0.01
epsilon_decay_rate: 0.9999
discount_factor: 0.99

#Training_Args:
episodes: 1500
time_step: 0.05
batch_size: 64
target_update_freq: 500
replay_buffer_size: 10000
output_dir: '/Users/adriancosio/Projects/cartpole-dqn/results'
